# Generated by Django 6.0.7 on 2026-08-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_fix_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(choices=[('PANTALLAS', 'Pantallas'), ('BATERIAS', 'Baterías'), ('CONECTORES', 'Conectores'), ('CAMARAS', 'Cámaras'), ('OTROS', 'Otros')], default='OTROS', max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
