# Generated by Django 6.0.7 on 2026-08-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
    ]
