# Generated by Django 6.0.7 on 2026-08-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_add_foto_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='categoria',
            field=models.CharField(choices=[('PANTALLAS', 'Pantallas / LCD'), ('BATERIAS', 'Baterías'), ('CONECTORES', 'Conectores'), ('CAMARAS', 'Cámaras'), ('ADHESIVOS', 'Adhesivos / Químicos'), ('MODULOS', 'Módulos Display'), ('OTROS', 'Repuestos Generales')], default='OTROS', max_length=50),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
