# Generated by Django 6.0.7 on 2026-08-05 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_repuesto_add_proveedor_default_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'Nivel 1 — Mantenimiento básico, formateo y repuestos modulares'), (2, 'Nivel 2 — Software avanzado, firmware y reparación de chasis/conectores'), (3, 'Nivel 3 — Microelectrónica y microsoldadura en placa base')], default=1, verbose_name='Nivel de Competencia')),
                ('especialidades', models.CharField(blank=True, default='', help_text='Lista separada por comas: CELULAR, PC_MESA, PORTATIL', max_length=100, verbose_name='Dispositivos que atiende')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones internas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tecnico', models.OneToOneField(limit_choices_to={'rol': 'TECNICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Técnico',
                'verbose_name_plural': 'Perfiles de Técnicos',
            },
        ),
    ]
