# Generated by Django 6.0.7 on 2026-08-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_add_perfil_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='repuestos/', verbose_name='Foto del Repuesto'),
        ),
    ]
