# Generated by Django 6.0.7 on 2026-08-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_add_repuesto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3')], default=1),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
