# Generated by Django 6.0.7 on 2026-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_servicio_nivel_servicio_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiltecnico',
            name='especialidades',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
        migrations.AddField(
            model_name='perfiltecnico',
            name='especialidad',
            field=models.CharField(choices=[('tecnico_celular', 'Especialista en Celulares'), ('tecnico_pc', 'Especialista en PC de mesa'), ('tecnico_laptop', 'Especialista en Portátiles/Laptops'), ('tecnico_general', 'Técnico General (Todos)')], default='tecnico_general', max_length=30, verbose_name='Especialidad Técnica'),
        ),
    ]
