# Generated by Django 6.0.7 on 2026-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_remove_perfiltecnico_especialidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltecnico',
            name='en_pausa_manual',
            field=models.BooleanField(default=False, verbose_name='Pausa Manual'),
        ),
    ]
