# Generated by Django 6.0.7 on 2026-08-11 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_perfiltecnico_en_pausa_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_serial', models.CharField(blank=True, help_text='IMEI o Número de Serie', max_length=100, null=True, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CELULAR', 'Celular'), ('LAPTOP', 'Laptop / PC'), ('TABLET', 'Tablet'), ('CONSOLA', 'Consola'), ('OTRO', 'Otro')], default='CELULAR', max_length=20)),
                ('detalles', models.TextField(blank=True, help_text='Color, capacidad, estado estético...', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_dispositivo', to='turnos.dispositivo'),
        ),
    ]
