# Generated by Django 6.0.7 on 2026-08-13 03:03

from django.db import migrations, models

# ---------------------------------------------------------------------------
# Función PL/pgSQL compartida por todos los triggers de auditoría.
# Detecta la tabla que dispara el evento y registra en auditoria_log.
# ---------------------------------------------------------------------------
CREATE_AUDIT_FUNCTION = """
CREATE OR REPLACE FUNCTION fn_auditoria_generica()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_tabla     TEXT;
    v_id        BIGINT;
    v_antes     JSONB;
    v_despues   JSONB;
BEGIN
    -- TG_ARGV[0] contiene la etiqueta de tabla pasada al crear el trigger
    v_tabla := TG_ARGV[0];

    IF (TG_OP = 'INSERT') THEN
        v_antes   := NULL;
        v_despues := to_jsonb(NEW);
        BEGIN v_id := (to_jsonb(NEW)->>'id')::BIGINT; EXCEPTION WHEN others THEN v_id := NULL; END;

    ELSIF (TG_OP = 'UPDATE') THEN
        v_antes   := to_jsonb(OLD);
        v_despues := to_jsonb(NEW);
        BEGIN v_id := (to_jsonb(NEW)->>'id')::BIGINT; EXCEPTION WHEN others THEN v_id := NULL; END;

    ELSIF (TG_OP = 'DELETE') THEN
        v_antes   := to_jsonb(OLD);
        v_despues := NULL;
        BEGIN v_id := (to_jsonb(OLD)->>'id')::BIGINT; EXCEPTION WHEN others THEN v_id := NULL; END;
    END IF;

    INSERT INTO auditoria_log
        (tabla, operacion, registro_id, datos_antes, datos_despues, usuario_db, ip_cliente, fecha)
    VALUES
        (v_tabla, TG_OP, v_id, v_antes, v_despues, current_user, inet_client_addr(), NOW());

    RETURN NEW;
END;
$$;
"""

DROP_AUDIT_FUNCTION = "DROP FUNCTION IF EXISTS fn_auditoria_generica() CASCADE;"

# ---------------------------------------------------------------------------
# Triggers sobre las 4 tablas
# ---------------------------------------------------------------------------
TRIGGERS = [
    # Citas
    ("trg_auditoria_citas",    "turnos_cita",     "citas"),
    # Clientes (rol CLIENTE en turnos_usuario)
    ("trg_auditoria_clientes", "turnos_usuario",  "clientes"),
    # Personas = mismo origen pero etiqueta diferente para distinción semántica
    # (se puede separar por rol en la función si se necesita)
    ("trg_auditoria_personas", "turnos_usuario",  "personas"),
    # Sesiones
    ("trg_auditoria_sesiones", "django_session",  "sesiones"),
]

def create_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(CREATE_AUDIT_FUNCTION)
    for trigger_name, table_name, etiqueta in TRIGGERS:
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger_name} ON {table_name};")
        schema_editor.execute(f"""
            CREATE TRIGGER {trigger_name}
            AFTER INSERT OR UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION fn_auditoria_generica('{etiqueta}');
        """)

def drop_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for trigger_name, table_name, _ in TRIGGERS:
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS {trigger_name} ON {table_name};"
        )
    schema_editor.execute(DROP_AUDIT_FUNCTION)


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0012_dispositivo_cita_dispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(choices=[('citas', 'Citas'), ('clientes', 'Clientes'), ('personas', 'Personas'), ('sesiones', 'Sesiones')], max_length=50)),
                ('operacion', models.CharField(choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10)),
                ('registro_id', models.BigIntegerField(blank=True, help_text='PK del registro afectado', null=True)),
                ('datos_antes', models.JSONField(blank=True, help_text='Valores anteriores (UPDATE/DELETE)', null=True)),
                ('datos_despues', models.JSONField(blank=True, help_text='Valores nuevos (INSERT/UPDATE)', null=True)),
                ('usuario_db', models.CharField(blank=True, help_text='Usuario de base de datos', max_length=150, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'auditoria_log',
                'ordering': ['-fecha'],
            },
        ),
        # Crear función y triggers en Postgres
        migrations.RunPython(create_triggers, reverse_code=drop_triggers),
    ]
