# Generated by Django 6.0.7 on 2026-08-11 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0012_dispositivo_cita_dispositivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'Mantenimiento'), ('fallo', 'Fallo / Interrupción')], default='operativo', max_length=20)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('urgencia', models.CharField(choices=[('Alta', 'Alta (Crítica)'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('revision', 'En Revisión'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_soporte_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
