# Generated by Django 6.0.7 on 2026-08-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_estadosistema_ticketsoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, null=True),
        ),
    ]
