# Generated by Django 6.0.7 on 2026-08-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_add_auditoria_log_and_triggers'),
        ('turnos', '0014_usuario_genero'),
    ]

    operations = [
    ]
