# Generated by Django 6.0.7 on 2026-08-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0015_merge_20260814_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita_repuestos', to='turnos.cita')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cita_repuestos', to='turnos.repuesto')),
            ],
            options={
                'unique_together': {('cita', 'repuesto')},
            },
        ),
        migrations.DeleteModel(
            name='AuditoriaLog',
        ),
    ]
