# Generated by Django 6.0.7 on 2026-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0016_add_cita_repuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(choices=[('citas', 'Citas'), ('clientes', 'Clientes'), ('personas', 'Personas'), ('sesiones', 'Sesiones')], max_length=50)),
                ('operacion', models.CharField(choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10)),
                ('registro_id', models.BigIntegerField(blank=True, help_text='PK del registro afectado', null=True)),
                ('datos_antes', models.JSONField(blank=True, help_text='Valores anteriores (UPDATE/DELETE)', null=True)),
                ('datos_despues', models.JSONField(blank=True, help_text='Valores nuevos (INSERT/UPDATE)', null=True)),
                ('usuario_db', models.CharField(blank=True, help_text='Usuario de base de datos', max_length=150, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'auditoria_log',
                'ordering': ['-fecha'],
            },
        ),
    ]
